[package]
name = "cookie"
version = "0.15.0-dev"
authors = ["Sergio Benitez <sb@sergio.bz>", "Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/SergioBenitez/cookie-rs"
documentation = "https://docs.rs/cookie"
readme = "README.md"
build = "build.rs"
description = """
HTTP cookie parsing and cookie jar management. Supports signed and private
(encrypted, authenticated) jars.
"""

[features]
percent-encode = ["percent-encoding"]
secure = ["private", "signed", "key-expansion"]
private = ["aes-gcm", "base64", "rand"]
signed = ["hmac", "sha2", "base64", "rand"]
key-expansion = ["sha2", "hkdf"]

[dependencies]
time = { version = "0.2.11", default-features = false, features = ["std"] }
percent-encoding = { version = "2.0", optional = true }
dashmap = "4.0.0-rc6"

# dependencies for secure (private/signed) functionality
aes-gcm = { version = "0.6.0", optional = true }
hmac = { version = "0.8.0", optional = true }
sha2 = { version = "0.9.0", optional = true }
base64 = { version = "0.13", optional = true }
rand = { version = "0.7.3", optional = true }
hkdf = { version = "0.9.0", optional = true }

[build-dependencies]
version_check = "0.9"

[package.metadata.docs.rs]
all-features = true
