[package]

name = "cookie"
authors = ["Alex Crichton <alex@alexcrichton.com>", "Sergio Benitez <sb@sergio.bz>"]
version = "0.7.5"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/cookie-rs"
documentation = "https://docs.rs/cookie"
description = """
Crate for parsing HTTP cookie headers and managing a cookie jar. Supports signed
and private (encrypted + signed) jars.
"""

[features]
secure = ["ring", "base64"]
percent-encode = ["url"]

[dependencies]
chrono = "0.3.1"
url = { version = "1.0", optional = true }
ring = { version = "0.7.4", optional = true }
base64 = { version = "0.4", optional = true }
