name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "${{ matrix.os.name }} (${{ matrix.toolchain }})"
    continue-on-error: false
    runs-on: ${{ matrix.os.distro }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Linux, distro: ubuntu-latest }
          - { name: Windows, distro: windows-latest }
        toolchain: [stable, beta, nightly]

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Run Tests
        run: ./scripts/test.sh
        shell: bash
